WholeSalesApp/Plugins/Nop.Plugin.Payments.2C2P/Controllers/Payment2C2PController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using My2C2PPKCS7;
using Newtonsoft.Json;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Core.Http.Extensions;
using Nop.Plugin.Payments._2C2P.Models;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments._2C2P.Controllers
{
    // Created by Alexandar Rajavel on 14-Mar-2019
    public class Payment2C2PController : BasePaymentController
    {

        #region Fields

        private readonly IWorkContext _workContext;
        private readonly IStoreService _storeService;
        private readonly ISettingService _settingService;
        private readonly IPaymentService _paymentService;
        private readonly IOrderService _orderService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IPermissionService _permissionService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ILocalizationService _localizationService;
        private readonly IStoreContext _storeContext;
        private readonly ILogger _logger;
        private readonly IWebHelper _webHelper;
        private readonly PaymentSettings _paymentSettings;
        private readonly _2C2PPaymentSettings _2C2PPaymentSettings;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICustomerService _customerService;
        private readonly IPaymentTransactionHistoryService _paymentTransactionHistoryService;
        private readonly INotificationService _notificationService;

        #endregion

        #region Constructor
        public Payment2C2PController(IWorkContext workContext,
            IStoreService storeService,
            ISettingService settingService,
            IPaymentService paymentService,
            IOrderService orderService,
            IOrderProcessingService orderProcessingService,
            IPermissionService permissionService,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            IStoreContext storeContext,
            ILogger logger,
            IWebHelper webHelper,
            PaymentSettings paymentSettings,
            _2C2PPaymentSettings twoC2PPaymentSettings,
            ShoppingCartSettings shoppingCartSettings,
            IHttpContextAccessor httpContextAccessor,
            ICustomerService customerService,
            IPaymentTransactionHistoryService paymentTransactionHistoryService,
            INotificationService notificationService)
        {

            this._workContext = workContext;
            this._storeService = storeService;
            this._settingService = settingService;
            this._paymentService = paymentService;
            this._orderService = orderService;
            this._orderProcessingService = orderProcessingService;
            this._permissionService = permissionService;
            this._genericAttributeService = genericAttributeService;
            this._localizationService = localizationService;
            this._storeContext = storeContext;
            this._logger = logger;
            this._webHelper = webHelper;
            this._paymentSettings = paymentSettings;
            _2C2PPaymentSettings = twoC2PPaymentSettings;
            this._shoppingCartSettings = shoppingCartSettings;
            this._httpContextAccessor = httpContextAccessor;
            this._customerService = customerService;
            this._paymentTransactionHistoryService = paymentTransactionHistoryService;
            _notificationService = notificationService;
        }
        #endregion

        #region Methods
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            //var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var paymentSettings2C2P = _settingService.LoadSetting<_2C2PPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                UseSandbox = paymentSettings2C2P.UseSandbox,
                Version = paymentSettings2C2P.Version,
                MerchantId = paymentSettings2C2P.MerchantId,
                SecretKey = paymentSettings2C2P.SecretKey,
                ResultUrl = paymentSettings2C2P.ResultUrl,
                Currency = paymentSettings2C2P.Currency,
                AdditionalFee = paymentSettings2C2P.AdditionalFee,
                AdditionalFeePercentage = paymentSettings2C2P.AdditionalFeePercentage,
                PassProductNamesAndTotals = paymentSettings2C2P.PassProductNamesAndTotals,
                RedirectAndPostDataURL = paymentSettings2C2P.RedirectAndPostDataURL,
                PrivatePfxFilePath = paymentSettings2C2P.PrivatePfxFilePath,
                PrivatePfxFilePassword = paymentSettings2C2P.PrivatePfxFilePassword
            };
            if (storeScope > 0)
            {
                model.UseSandbox_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.UseSandbox, storeScope);
                model.Version_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.Version, storeScope);
                model.MerchantId_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.MerchantId, storeScope);
                model.SecretKey_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.SecretKey, storeScope);
                model.ResultUrl_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.ResultUrl, storeScope);
                model.Currency_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.Currency, storeScope);
                model.AdditionalFee_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.AdditionalFeePercentage, storeScope);
                model.PassProductNamesAndTotals_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.PassProductNamesAndTotals, storeScope);
                model.RedirectAndPostDataURL_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.RedirectAndPostDataURL, storeScope);
                model.PrivatePfxFilePath_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.PrivatePfxFilePath, storeScope);
                model.PrivatePfxFilePassword_OverrideForStore = _settingService.SettingExists(paymentSettings2C2P, x => x.PrivatePfxFilePassword, storeScope);
            }

            return View("~/Plugins/Payments.2C2P/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //load settings for a chosen store scope
            //var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var paymentSettings2C2P = _settingService.LoadSetting<_2C2PPaymentSettings>(storeScope);

            //save settings
            paymentSettings2C2P.UseSandbox = model.UseSandbox;
            paymentSettings2C2P.Version = model.Version;
            paymentSettings2C2P.MerchantId = model.MerchantId;
            paymentSettings2C2P.SecretKey = model.SecretKey;
            paymentSettings2C2P.ResultUrl = model.ResultUrl;
            paymentSettings2C2P.Currency = model.Currency;
            paymentSettings2C2P.AdditionalFee = model.AdditionalFee;
            paymentSettings2C2P.AdditionalFeePercentage = model.AdditionalFeePercentage;
            paymentSettings2C2P.PassProductNamesAndTotals = model.PassProductNamesAndTotals;
            paymentSettings2C2P.RedirectAndPostDataURL = model.RedirectAndPostDataURL;
            paymentSettings2C2P.PrivatePfxFilePath = model.PrivatePfxFilePath;
            paymentSettings2C2P.PrivatePfxFilePassword = model.PrivatePfxFilePassword;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            _settingService.SaveSettingOverridablePerStore(paymentSettings2C2P, x => x.UseSandbox, model.UseSandbox_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(paymentSettings2C2P, x => x.Version, model.Version_OverrideForStore, storeScope, false);

WholeSalesApp/Plugins/Nop.Plugin.Payments.2C2P/Views/Configure.cshtml
@model Nop.Plugin.Payments._2C2P.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}
@await Component.InvokeAsync("StoreScopeConfiguration")


<form asp-controller="Payment2C2P" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Version_OverrideForStore" asp-input="Version" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Version" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Version" />
                        <span asp-validation-for="Version"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="MerchantId_OverrideForStore" asp-input="MerchantId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SecretKey_OverrideForStore" asp-input="SecretKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SecretKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecretKey" />
                        <span asp-validation-for="SecretKey"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ResultUrl_OverrideForStore" asp-input="ResultUrl" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ResultUrl" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ResultUrl" />
                        <span asp-validation-for="ResultUrl"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Currency_OverrideForStore" asp-input="Currency" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Currency" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Currency" />
                        <span asp-validation-for="Currency"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PrivatePfxFilePath_OverrideForStore" asp-input="PrivatePfxFilePath" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PrivatePfxFilePath" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PrivatePfxFilePath" />
                        <span asp-validation-for="PrivatePfxFilePath"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PrivatePfxFilePassword_OverrideForStore" asp-input="PrivatePfxFilePassword" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PrivatePfxFilePassword" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PrivatePfxFilePassword" />
                        <span asp-validation-for="PrivatePfxFilePassword"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="RedirectAndPostDataURL_OverrideForStore" asp-input="RedirectAndPostDataURL" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="RedirectAndPostDataURL" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="RedirectAndPostDataURL" />
                        <span asp-validation-for="RedirectAndPostDataURL"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

WholeSalesApp/Plugins/Nop.Plugin.Payments.2C2P/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.2C2P.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
</table>